---
- name: Change a user's password on Windows
  hosts: "{{ host }}"
  vars:
    ansible_shell_type: powershell
  vars_files:
    - /vars/secret_vars.yml
  tasks:
    - name: Change user password
      win_user:
        name: "labadmin"
        password: "{{ user_password }}"
        update_password: always
        state: present
